name: Suggest Adding A VR Headset to the database
description: Help Let Us Know About A VR Headset to Add to the database
title: "[Headset Suggestion]: "

body: 
  - type: input
    id: headsetName
    attributes: 
      label: Headset Name
      description: The name of the VR Headset you are trying to suggest.
      placeholder: ex. Oculus Go
    validations:
      required: true
  - type: input
    id: headsetCodename
    attributes:
      label: Codename of said VR Headset
      description: Codename for the VR Headset you are suggesting. Can Be Skipped.
      placeholder: ex. Pacific
    validations:
      required: false
